/*
 * Copyright (C) 2021 Jordan Hendl
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* 
 * File:   Connection.h
 * Author: Jordan Hendl
 *
 * Created on January 18, 2021, 9:56 PM
 */

#ifndef YGGDRASIL_CONNECTION_H
#define YGGDRASIL_CONNECTION_H

namespace ygg
{
    /** The default size of a packet.
   */
  static const unsigned PACKET_SIZE = 8000 ;
  
  /** Forward decalare
   */
  class Packet ;
  
  namespace lx
  {
    class Connection ;
  }
  
  namespace win32
  {
    class Connection ;
  }
  
  namespace http
  {
    class Parser ;
  }

  /** The type of connections available.
   */
  enum class ConnectionType
  {
    None,
    Client,
    Server
  };
 
    /** Helper method to create a packet.
   * @param data The pointer to use for the packet's data.
   * @param data_amt The amount of data in the pointer to copy into the packet.
   * @return A Packet generated by the input data.
   */
  Packet makePacket( const char* data, unsigned data_amt ) ;

  /** Class for managing each data package sent and recieved from a connection.
   */
  class Packet
  {
    public:
      
      /** Default constructor.
       */
      Packet() ;
      
      /** Copy constructor.
       * @param packet The packet to copy into this one.
       */
      Packet( const Packet& packet ) ;
      
      /** Deconstructor.
       */
      ~Packet() ;
      
      /** Assignment operator. Copies input packet into this one.
       * @param packet The packet to copy.
       * @return Reference to this object after assignment.
       */
      Packet& operator=( const Packet& packet ) ;
      
      /** Method to retrieve the size in bytes of this packet.
       * @return The size in bytes of data that this packet contains.
       */
      unsigned size() const ;
      
      /** Method to retrieve the payload of this packet.
       * @note The payloca contains the amount of data specified by Packet::size().
       * @return The constant pointer to the start of this object's data.
       */
      const char* payload() const ;
      
    private:
      
      /** Friend declerations for OS-specific classes.
       */
      friend class lx::Connection    ;
//      friend class win32::Connection ;
      friend class http::Parser      ;

      /** Friend function to make a packet.
       */
      friend Packet makePacket( const char* data, unsigned data_amt ) ;

      /** The data container of this class.
       */
      char     data_ptr[ PACKET_SIZE ] ;
      
      /** The amount of data being stored in this object's data container.
       */
      unsigned data_size ;
  };

  /** Library object to handle a connection.
   */
  template<typename Impl>
  class Connection
  {
    public:
      
      /** Default constructor.
       */
      Connection() = default ;
      
      /** Default deconstructor.
       */
      ~Connection() = default ;
      
      /** Conversion operator to convert this object to the underlying implementation's version.
       * @return The underlying implementation's connection object.
       */
      operator const typename Impl::Connection&() ;
      
      /** Method to start a connection.
       * @param host The C-string representation of the host name to connect to.
       * @param port The port number to use.
       * @param type The type of connection to make.
       */
      void connect( const char* host, ygg::ConnectionType type = ygg::ConnectionType::Client, unsigned port = 80 ) ;
      
      /** Method to retrieve whether or not this connection is successfully connected.
       * @return Whether or not this connection is valid & working correctly.
       */
      bool valid() const ;
      
      /** Method to send a message over the connection & retrieve a response.
       * @param command The command to send.
       */
      void send( const char* command, unsigned size ) ;
      
      /** Method to retrieve a message from the connection.
       * @return The data recieved from the connection.
       */
      Packet recieve( unsigned size = 8000 ) ;
      
      /** Method to reset this connection & end all traffic.
       */
      void reset() ;
    private:
      
      /** The underlying connection object.
       */
      typename Impl::Connection connection ;
  };
  
  template<typename Impl>
  Connection<Impl>::operator const typename Impl::Connection&()
  {
    return this->connection ;
  }
  
  template<typename Impl>
  void Connection<Impl>::connect( const char* host, ygg::ConnectionType type, unsigned port )
  {
    this->connection.connect( host, type, port ) ;
  }
  
  template<typename Impl>
  void Connection<Impl>::send( const char* command, unsigned size )
  {
    this->connection.send( command, size ) ;
  }
  
  template<typename Impl>
  bool Connection<Impl>::valid() const
  {
    return this->connection.valid() ;
  }
  
  template<typename Impl>
  Packet Connection<Impl>::recieve( unsigned size )
  {
    return this->connection.recieve( size ) ;
  }
  
  template<typename Impl>
  void Connection<Impl>::reset()
  {
    this->connection.reset() ;
  }
}

#endif /* CONNECTION_H */

